//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idProject { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> idStatus { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual StatusTask StatusTask { get; set; }
        public virtual User User { get; set; }
    }
}
