//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idTask { get; set; }
    
        public virtual User User { get; set; }
    }
}
